/**
 * ISO-3166 alpha-2 country list shown in the booker-info form's
 * residence-country picker. Stored on Passenger.countryCode.
 *
 * Names are pulled from Korean MOFA's standard country name table for
 * the KO column and the Unicode CLDR "en" locale for the EN column.
 * Sorted by ISO code for stable rendering; the picker re-sorts by the
 * active language at display time.
 */
export type Country = {
  /** ISO-3166 alpha-2 — primary key stored on the order. */
  iso: string;
  /** Display name in Korean. */
  ko: string;
  /** Display name in English. */
  en: string;
};

export const COUNTRIES: Country[] = [
  { iso: "AD", ko: "안도라", en: "Andorra" },
  { iso: "AE", ko: "아랍에미리트", en: "United Arab Emirates" },
  { iso: "AF", ko: "아프가니스탄", en: "Afghanistan" },
  { iso: "AG", ko: "앤티가 바부다", en: "Antigua and Barbuda" },
  { iso: "AI", ko: "앵귈라", en: "Anguilla" },
  { iso: "AL", ko: "알바니아", en: "Albania" },
  { iso: "AM", ko: "아르메니아", en: "Armenia" },
  { iso: "AO", ko: "앙골라", en: "Angola" },
  { iso: "AR", ko: "아르헨티나", en: "Argentina" },
  { iso: "AS", ko: "미국령 사모아", en: "American Samoa" },
  { iso: "AT", ko: "오스트리아", en: "Austria" },
  { iso: "AU", ko: "호주", en: "Australia" },
  { iso: "AW", ko: "아루바", en: "Aruba" },
  { iso: "AX", ko: "올란드 제도", en: "Åland Islands" },
  { iso: "AZ", ko: "아제르바이잔", en: "Azerbaijan" },
  { iso: "BA", ko: "보스니아 헤르체고비나", en: "Bosnia and Herzegovina" },
  { iso: "BB", ko: "바베이도스", en: "Barbados" },
  { iso: "BD", ko: "방글라데시", en: "Bangladesh" },
  { iso: "BE", ko: "벨기에", en: "Belgium" },
  { iso: "BF", ko: "부르키나파소", en: "Burkina Faso" },
  { iso: "BG", ko: "불가리아", en: "Bulgaria" },
  { iso: "BH", ko: "바레인", en: "Bahrain" },
  { iso: "BI", ko: "부룬디", en: "Burundi" },
  { iso: "BJ", ko: "베냉", en: "Benin" },
  { iso: "BL", ko: "생바르텔레미", en: "Saint Barthélemy" },
  { iso: "BM", ko: "버뮤다", en: "Bermuda" },
  { iso: "BN", ko: "브루나이", en: "Brunei Darussalam" },
  { iso: "BO", ko: "볼리비아", en: "Bolivia" },
  { iso: "BQ", ko: "보네르 신트외스타티위스 사바", en: "Bonaire, Sint Eustatius and Saba" },
  { iso: "BR", ko: "브라질", en: "Brazil" },
  { iso: "BS", ko: "바하마", en: "Bahamas" },
  { iso: "BT", ko: "부탄", en: "Bhutan" },
  { iso: "BW", ko: "보츠와나", en: "Botswana" },
  { iso: "BY", ko: "벨라루스", en: "Belarus" },
  { iso: "BZ", ko: "벨리즈", en: "Belize" },
  { iso: "CA", ko: "캐나다", en: "Canada" },
  { iso: "CC", ko: "코코스 제도", en: "Cocos (Keeling) Islands" },
  { iso: "CD", ko: "콩고민주공화국", en: "Congo, Democratic Republic of the" },
  { iso: "CF", ko: "중앙아프리카공화국", en: "Central African Republic" },
  { iso: "CG", ko: "콩고", en: "Congo" },
  { iso: "CH", ko: "스위스", en: "Switzerland" },
  { iso: "CI", ko: "코트디부아르", en: "Côte d'Ivoire" },
  { iso: "CK", ko: "쿡 제도", en: "Cook Islands" },
  { iso: "CL", ko: "칠레", en: "Chile" },
  { iso: "CM", ko: "카메룬", en: "Cameroon" },
  { iso: "CN", ko: "중국", en: "China" },
  { iso: "CO", ko: "콜롬비아", en: "Colombia" },
  { iso: "CR", ko: "코스타리카", en: "Costa Rica" },
  { iso: "CU", ko: "쿠바", en: "Cuba" },
  { iso: "CV", ko: "카보베르데", en: "Cabo Verde" },
  { iso: "CW", ko: "퀴라소", en: "Curaçao" },
  { iso: "CX", ko: "크리스마스섬", en: "Christmas Island" },
  { iso: "CY", ko: "키프로스", en: "Cyprus" },
  { iso: "CZ", ko: "체코", en: "Czechia" },
  { iso: "DE", ko: "독일", en: "Germany" },
  { iso: "DJ", ko: "지부티", en: "Djibouti" },
  { iso: "DK", ko: "덴마크", en: "Denmark" },
  { iso: "DM", ko: "도미니카연방", en: "Dominica" },
  { iso: "DO", ko: "도미니카공화국", en: "Dominican Republic" },
  { iso: "DZ", ko: "알제리", en: "Algeria" },
  { iso: "EC", ko: "에콰도르", en: "Ecuador" },
  { iso: "EE", ko: "에스토니아", en: "Estonia" },
  { iso: "EG", ko: "이집트", en: "Egypt" },
  { iso: "EH", ko: "서사하라", en: "Western Sahara" },
  { iso: "ER", ko: "에리트레아", en: "Eritrea" },
  { iso: "ES", ko: "스페인", en: "Spain" },
  { iso: "ET", ko: "에티오피아", en: "Ethiopia" },
  { iso: "FI", ko: "핀란드", en: "Finland" },
  { iso: "FJ", ko: "피지", en: "Fiji" },
  { iso: "FK", ko: "포클랜드 제도", en: "Falkland Islands" },
  { iso: "FM", ko: "미크로네시아연방", en: "Micronesia, Federated States of" },
  { iso: "FO", ko: "페로 제도", en: "Faroe Islands" },
  { iso: "FR", ko: "프랑스", en: "France" },
  { iso: "GA", ko: "가봉", en: "Gabon" },
  { iso: "GB", ko: "영국", en: "United Kingdom" },
  { iso: "GD", ko: "그레나다", en: "Grenada" },
  { iso: "GE", ko: "조지아", en: "Georgia" },
  { iso: "GF", ko: "프랑스령 기아나", en: "French Guiana" },
  { iso: "GG", ko: "건지섬", en: "Guernsey" },
  { iso: "GH", ko: "가나", en: "Ghana" },
  { iso: "GI", ko: "지브롤터", en: "Gibraltar" },
  { iso: "GL", ko: "그린란드", en: "Greenland" },
  { iso: "GM", ko: "감비아", en: "Gambia" },
  { iso: "GN", ko: "기니", en: "Guinea" },
  { iso: "GP", ko: "과들루프", en: "Guadeloupe" },
  { iso: "GQ", ko: "적도 기니", en: "Equatorial Guinea" },
  { iso: "GR", ko: "그리스", en: "Greece" },
  { iso: "GT", ko: "과테말라", en: "Guatemala" },
  { iso: "GU", ko: "괌", en: "Guam" },
  { iso: "GW", ko: "기니비사우", en: "Guinea-Bissau" },
  { iso: "GY", ko: "가이아나", en: "Guyana" },
  { iso: "HK", ko: "홍콩", en: "Hong Kong" },
  { iso: "HN", ko: "온두라스", en: "Honduras" },
  { iso: "HR", ko: "크로아티아", en: "Croatia" },
  { iso: "HT", ko: "아이티", en: "Haiti" },
  { iso: "HU", ko: "헝가리", en: "Hungary" },
  { iso: "ID", ko: "인도네시아", en: "Indonesia" },
  { iso: "IE", ko: "아일랜드", en: "Ireland" },
  { iso: "IL", ko: "이스라엘", en: "Israel" },
  { iso: "IM", ko: "맨섬", en: "Isle of Man" },
  { iso: "IN", ko: "인도", en: "India" },
  { iso: "IO", ko: "영국령 인도양 지역", en: "British Indian Ocean Territory" },
  { iso: "IQ", ko: "이라크", en: "Iraq" },
  { iso: "IR", ko: "이란", en: "Iran" },
  { iso: "IS", ko: "아이슬란드", en: "Iceland" },
  { iso: "IT", ko: "이탈리아", en: "Italy" },
  { iso: "JE", ko: "저지섬", en: "Jersey" },
  { iso: "JM", ko: "자메이카", en: "Jamaica" },
  { iso: "JO", ko: "요르단", en: "Jordan" },
  { iso: "JP", ko: "일본", en: "Japan" },
  { iso: "KE", ko: "케냐", en: "Kenya" },
  { iso: "KG", ko: "키르기스스탄", en: "Kyrgyzstan" },
  { iso: "KH", ko: "캄보디아", en: "Cambodia" },
  { iso: "KI", ko: "키리바시", en: "Kiribati" },
  { iso: "KM", ko: "코모로", en: "Comoros" },
  { iso: "KN", ko: "세인트키츠 네비스", en: "Saint Kitts and Nevis" },
  { iso: "KP", ko: "북한", en: "North Korea" },
  { iso: "KR", ko: "대한민국", en: "South Korea" },
  { iso: "KW", ko: "쿠웨이트", en: "Kuwait" },
  { iso: "KY", ko: "케이맨 제도", en: "Cayman Islands" },
  { iso: "KZ", ko: "카자흐스탄", en: "Kazakhstan" },
  { iso: "LA", ko: "라오스", en: "Laos" },
  { iso: "LB", ko: "레바논", en: "Lebanon" },
  { iso: "LC", ko: "세인트루시아", en: "Saint Lucia" },
  { iso: "LI", ko: "리히텐슈타인", en: "Liechtenstein" },
  { iso: "LK", ko: "스리랑카", en: "Sri Lanka" },
  { iso: "LR", ko: "라이베리아", en: "Liberia" },
  { iso: "LS", ko: "레소토", en: "Lesotho" },
  { iso: "LT", ko: "리투아니아", en: "Lithuania" },
  { iso: "LU", ko: "룩셈부르크", en: "Luxembourg" },
  { iso: "LV", ko: "라트비아", en: "Latvia" },
  { iso: "LY", ko: "리비아", en: "Libya" },
  { iso: "MA", ko: "모로코", en: "Morocco" },
  { iso: "MC", ko: "모나코", en: "Monaco" },
  { iso: "MD", ko: "몰도바", en: "Moldova" },
  { iso: "ME", ko: "몬테네그로", en: "Montenegro" },
  { iso: "MF", ko: "생마르탱", en: "Saint Martin (French part)" },
  { iso: "MG", ko: "마다가스카르", en: "Madagascar" },
  { iso: "MH", ko: "마셜 제도", en: "Marshall Islands" },
  { iso: "MK", ko: "북마케도니아", en: "North Macedonia" },
  { iso: "ML", ko: "말리", en: "Mali" },
  { iso: "MM", ko: "미얀마", en: "Myanmar" },
  { iso: "MN", ko: "몽골", en: "Mongolia" },
  { iso: "MO", ko: "마카오", en: "Macao" },
  { iso: "MP", ko: "북마리아나 제도", en: "Northern Mariana Islands" },
  { iso: "MQ", ko: "마르티니크", en: "Martinique" },
  { iso: "MR", ko: "모리타니", en: "Mauritania" },
  { iso: "MS", ko: "몬트세랫", en: "Montserrat" },
  { iso: "MT", ko: "몰타", en: "Malta" },
  { iso: "MU", ko: "모리셔스", en: "Mauritius" },
  { iso: "MV", ko: "몰디브", en: "Maldives" },
  { iso: "MW", ko: "말라위", en: "Malawi" },
  { iso: "MX", ko: "멕시코", en: "Mexico" },
  { iso: "MY", ko: "말레이시아", en: "Malaysia" },
  { iso: "MZ", ko: "모잠비크", en: "Mozambique" },
  { iso: "NA", ko: "나미비아", en: "Namibia" },
  { iso: "NC", ko: "뉴칼레도니아", en: "New Caledonia" },
  { iso: "NE", ko: "니제르", en: "Niger" },
  { iso: "NF", ko: "노퍽섬", en: "Norfolk Island" },
  { iso: "NG", ko: "나이지리아", en: "Nigeria" },
  { iso: "NI", ko: "니카라과", en: "Nicaragua" },
  { iso: "NL", ko: "네덜란드", en: "Netherlands" },
  { iso: "NO", ko: "노르웨이", en: "Norway" },
  { iso: "NP", ko: "네팔", en: "Nepal" },
  { iso: "NR", ko: "나우루", en: "Nauru" },
  { iso: "NU", ko: "니우에", en: "Niue" },
  { iso: "NZ", ko: "뉴질랜드", en: "New Zealand" },
  { iso: "OM", ko: "오만", en: "Oman" },
  { iso: "PA", ko: "파나마", en: "Panama" },
  { iso: "PE", ko: "페루", en: "Peru" },
  { iso: "PF", ko: "프랑스령 폴리네시아", en: "French Polynesia" },
  { iso: "PG", ko: "파푸아뉴기니", en: "Papua New Guinea" },
  { iso: "PH", ko: "필리핀", en: "Philippines" },
  { iso: "PK", ko: "파키스탄", en: "Pakistan" },
  { iso: "PL", ko: "폴란드", en: "Poland" },
  { iso: "PM", ko: "생피에르 미클롱", en: "Saint Pierre and Miquelon" },
  { iso: "PN", ko: "핏케언 제도", en: "Pitcairn" },
  { iso: "PR", ko: "푸에르토리코", en: "Puerto Rico" },
  { iso: "PS", ko: "팔레스타인", en: "Palestine" },
  { iso: "PT", ko: "포르투갈", en: "Portugal" },
  { iso: "PW", ko: "팔라우", en: "Palau" },
  { iso: "PY", ko: "파라과이", en: "Paraguay" },
  { iso: "QA", ko: "카타르", en: "Qatar" },
  { iso: "RE", ko: "레위니옹", en: "Réunion" },
  { iso: "RO", ko: "루마니아", en: "Romania" },
  { iso: "RS", ko: "세르비아", en: "Serbia" },
  { iso: "RU", ko: "러시아", en: "Russia" },
  { iso: "RW", ko: "르완다", en: "Rwanda" },
  { iso: "SA", ko: "사우디아라비아", en: "Saudi Arabia" },
  { iso: "SB", ko: "솔로몬 제도", en: "Solomon Islands" },
  { iso: "SC", ko: "세이셸", en: "Seychelles" },
  { iso: "SD", ko: "수단", en: "Sudan" },
  { iso: "SE", ko: "스웨덴", en: "Sweden" },
  { iso: "SG", ko: "싱가포르", en: "Singapore" },
  { iso: "SH", ko: "세인트헬레나", en: "Saint Helena" },
  { iso: "SI", ko: "슬로베니아", en: "Slovenia" },
  { iso: "SJ", ko: "스발바르 얀마옌", en: "Svalbard and Jan Mayen" },
  { iso: "SK", ko: "슬로바키아", en: "Slovakia" },
  { iso: "SL", ko: "시에라리온", en: "Sierra Leone" },
  { iso: "SM", ko: "산마리노", en: "San Marino" },
  { iso: "SN", ko: "세네갈", en: "Senegal" },
  { iso: "SO", ko: "소말리아", en: "Somalia" },
  { iso: "SR", ko: "수리남", en: "Suriname" },
  { iso: "SS", ko: "남수단", en: "South Sudan" },
  { iso: "ST", ko: "상투메 프린시페", en: "São Tomé and Príncipe" },
  { iso: "SV", ko: "엘살바도르", en: "El Salvador" },
  { iso: "SX", ko: "신트마르턴", en: "Sint Maarten (Dutch part)" },
  { iso: "SY", ko: "시리아", en: "Syrian Arab Republic" },
  { iso: "SZ", ko: "에스와티니", en: "Eswatini" },
  { iso: "TC", ko: "터크스 케이커스 제도", en: "Turks and Caicos Islands" },
  { iso: "TD", ko: "차드", en: "Chad" },
  { iso: "TG", ko: "토고", en: "Togo" },
  { iso: "TH", ko: "태국", en: "Thailand" },
  { iso: "TJ", ko: "타지키스탄", en: "Tajikistan" },
  { iso: "TK", ko: "토켈라우", en: "Tokelau" },
  { iso: "TL", ko: "동티모르", en: "Timor-Leste" },
  { iso: "TM", ko: "투르크메니스탄", en: "Turkmenistan" },
  { iso: "TN", ko: "튀니지", en: "Tunisia" },
  { iso: "TO", ko: "통가", en: "Tonga" },
  { iso: "TR", ko: "튀르키예", en: "Türkiye" },
  { iso: "TT", ko: "트리니다드 토바고", en: "Trinidad and Tobago" },
  { iso: "TV", ko: "투발루", en: "Tuvalu" },
  { iso: "TW", ko: "대만", en: "Taiwan" },
  { iso: "TZ", ko: "탄자니아", en: "Tanzania" },
  { iso: "UA", ko: "우크라이나", en: "Ukraine" },
  { iso: "UG", ko: "우간다", en: "Uganda" },
  { iso: "US", ko: "미국", en: "United States" },
  { iso: "UY", ko: "우루과이", en: "Uruguay" },
  { iso: "UZ", ko: "우즈베키스탄", en: "Uzbekistan" },
  { iso: "VA", ko: "바티칸", en: "Vatican City" },
  { iso: "VC", ko: "세인트빈센트 그레나딘", en: "Saint Vincent and the Grenadines" },
  { iso: "VE", ko: "베네수엘라", en: "Venezuela" },
  { iso: "VG", ko: "영국령 버진아일랜드", en: "British Virgin Islands" },
  { iso: "VI", ko: "미국령 버진아일랜드", en: "U.S. Virgin Islands" },
  { iso: "VN", ko: "베트남", en: "Vietnam" },
  { iso: "VU", ko: "바누아투", en: "Vanuatu" },
  { iso: "WF", ko: "왈리스 푸투나", en: "Wallis and Futuna" },
  { iso: "WS", ko: "사모아", en: "Samoa" },
  { iso: "XK", ko: "코소보", en: "Kosovo" },
  { iso: "YE", ko: "예멘", en: "Yemen" },
  { iso: "YT", ko: "마요트", en: "Mayotte" },
  { iso: "ZA", ko: "남아프리카공화국", en: "South Africa" },
  { iso: "ZM", ko: "잠비아", en: "Zambia" },
  { iso: "ZW", ko: "짐바브웨", en: "Zimbabwe" },
];

export function countryLabel(iso: string, lang: "ko" | "en"): string {
  const c = COUNTRIES.find((x) => x.iso === iso);
  if (!c) return iso;
  return lang === "ko" ? c.ko : c.en;
}
